export const UPDATE_START = 'UPDATE_START';
export const UPDATE_FINISH = 'UPDATE_FINISH';
export const SAVESETTINGS_START = 'SAVESETTINGS_START';
export const SAVESETTINGS_FINISH = 'SAVESETTINGS_FINISH';
