export const START_UPDATE = 'START_UPDATE';
export const END_UPDATE = 'END_UPDATE';
export const UPDATE_CAM_STATUS = 'UPDATE_CAM_STATUS';
export const UPDATE_SENSORS = 'UPDATE_SENSORS';
export const UPDATE_FILES = 'UPDATE_FILES';
export const DELETE_FILE = 'DELETE_FILE';
